brew "go"
brew "lua"
brew "vim"
brew "nvm"
brew "rust"
brew "ranger"
brew "yt-dlp"
brew "neofetch"
brew "onefetch"
brew "tty-clock"
brew "imagemagick"

# utilities
cask "vlc"
cask "keka"
cask "kid3"
cask "gimp"
cask "alfred"
cask "aldente"
cask "keycastr"
cask "inkscape"
cask "rectangle"
cask "imageoptim"
cask "balenaetcher"
cask "logi-options-plus"

# development tools
cask "hyper"
cask "docker"
cask "github"
cask "pieces"
cask "pomatez"
cask "obsidian"
cask "pieces-os"
cask "mongodb-compass"
cask "visual-studio-code"

cask "altserver"

# internet
cask "plex"
cask "zoom"
cask "steam"
cask "discord"
cask "firefox"
cask "megasync"
cask "miniconda"
cask "expressvpn"
cask "netnewswire"
cask "transmission"
cask "google-chrome"


# fonts
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-fira-sans"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "ultimaker-cura"
cask "whatsapp"