export const SubmoduleMetaInformation = {
	"alfred": { "path": "custom/alfred", "url": "https://github.com/stephansama/alfred", },
	"atuin": { "path": ".config/atuin", "url": "https://github.com/stephansama/atuin", },
	"bat": { "path": ".config/bat", "url": "https://github.com/stephansama/bat", },
	"firmware": { "path": "custom/firmware", "url": "https://github.com/stephansama/firmware", },
	"ghostty": { "path": ".config/ghostty", "url": "https://github.com/stephansama/ghostty", },
	"gitconfig": { "path": ".config/git", "url": "https://github.com/stephansama/gitconfig", },
	"hyprland": { "path": ".config/hypr", "url": "https://github.com/stephansama/hyprland", },
	"kitty": { "path": ".config/kitty", "url": "https://github.com/stephansama/kitty", },
	"lazygit": { "path": ".config/lazygit", "url": "https://github.com/stephansama/lazygit", },
	"mise": { "path": ".config/mise", "url": "https://github.com/stephansama/mise", },
	"nvim": { "path": ".config/nvim", "url": "https://github.com/stephansama/nvim", },
	"opencode": { "path": ".config/opencode", "url": "https://github.com/stephansama/opencode", },
	"refind": { "path": "custom/refind", "url": "https://github.com/stephansama/refind", },
	"rofi": { "path": ".config/rofi", "url": "https://github.com/stephansama/rofi", },
	"scripts": { "path": ".config/scripts", "url": "https://github.com/stephansama/scripts", },
	"sddm": { "path": "custom/sddm", "url": "https://github.com/stephansama/sddm", },
	"starship": { "path": ".config/starship", "url": "https://github.com/stephansama/starship", },
	"tmux": { "path": ".config/tmux", "url": "https://github.com/stephansama/tmux", },
	"vim": { "path": ".vim", "url": "https://github.com/stephansama/vim", },
	"wezterm": { "path": ".config/wezterm", "url": "https://github.com/stephansama/wezterm", },
	"yazi": { "path": ".config/yazi", "url": "https://github.com/stephansama/yazi", },
	"zellij": { "path": ".config/zellij", "url": "https://github.com/stephansama/zellij", },
	"zsh": { "path": "custom/zsh", "url": "https://github.com/stephansama/zsh", },
} as const
