name: Update git submodules
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
permissions:
  actions: write
  contents: write
  pull-requests: write
jobs:
  update:
    name: Update git submodules with the latest commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Update Submodules
        id: submodules
        uses: sgoudham/update-git-submodules@v2.1.3
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "feat: update all submodules"
          branch: "feat/update-all-submodules"
          title: "feat: update all submodules"
          body: ${{ steps.submodules.outputs.prBody }}
